### ISSUE TITLE
testing server dies.

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-server-data-gutenberg#11]
Here is the log:

Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]: Traceback (most recent call last):
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/bin/flask", line 8, in <module>
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     sys.exit(main())
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 990, in main
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     cli.main(args=sys.argv[1:])
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 596, in main
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return super().main(*args, **kwargs)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     rv = self.invoke(ctx)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return ctx.invoke(self.callback, **ctx.params)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return __callback(*args, **kwargs)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/decorators.py", line 84, in new_func
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return ctx.invoke(f, obj, *args, **kwargs)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     return __callback(*args, **kwargs)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 845, in run_command
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 321, in __init__
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     self._load_unlocked()
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 346, in _load_unlocked
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     self._app = rv = self.loader()
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 406, in load_app
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     app = locate_app(self, import_name, None, raise_if_not_found=False)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/.local/lib/python3.8/site-packages/flask/cli.py", line 256, in locate_app
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     __import__(module_name)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/bridges-server-data-gutenberg/app/__init__.py", line 8, in <module>
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     from app import routes
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/home/bridges-server-data-gutenberg-t/bridges-server-data-gutenberg/app/routes.py", line 498, in <module>
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     logging.basicConfig(format='%(asctime)s:  %(message)s', filename='log.log', encoding='utf-8', level=logging.INFO)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:   File "/usr/lib/python3.8/logging/__init__.py", line 1997, in basicConfig
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]:     raise ValueError('Unrecognised argument(s): %s' % keys)
Jun 21 15:12:35 ip-172-31-22-225 sh[1293166]: ValueError: Unrecognised argument(s): encoding

**Comment by esaule** [comment]
can start now. seems like there was a dependencies on testing package.
