### ISSUE TITLE
http://bridges-data-server-gutenberg.bridgesuncc.org//book?id=2701 return HTTP500 internal server error

### ISSUE THREAD

**Issue by esaule** [BridgesUNCC/bridges-server-data-gutenberg#14]

**Comment by esaule** [comment]
Seems to affect the prod server but not the testing server.
The prod server logs show:

```
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]: [2024-02-12 19:25:48,912] ERROR in app: Exception on /book [GET]
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]: Traceback (most recent call last):
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi>
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     response = self.full_dispatch_request()
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full>
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     rv = self.handle_user_exception(e)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full>
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     rv = self.dispatch_request()
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in disp>
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/bridges-server-data-gutenberg/app/routes.py", line 176, in downloadB>
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     LRU(num)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/home/bridges-server-data-gutenberg/bridges-server-data-gutenberg/app/routes.py", line 367, in LRU
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     lru = json.load(f)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     return loads(fp.read(),
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     return _default_decoder.decode(s)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Feb 12 19:25:48 ip-172-31-22-225 sh[1281822]: 127.0.0.1 - - [12/Feb/2024 19:25:48] "GET //book?id=10 HTTP/1.0" 500 -
```

**Comment by esaule** [comment]
It seems that the problem is that if there is no lru file, it dies trying to load it.
make sense the code has no exception case for can't load the file.

**Comment by esaule** [comment]
I think this should work now.

At some point we'll have to redo how our dataservers are being loaded, how much data  is available on the VM that host them, and upgrade the flask versions on the different dataserver and update the systemd start script.

maybe update the python version on the server as well.

currently still using python 3.8 on teh VM, and some packages (in particular click which processes command line arguments to flask) have silent bugs.
